language: cpp

sudo: false

compiler:
  - gcc

matrix:
  include:
    #- os: osx
    #  env: PLATFORM=mac DOCKERBUILD=0
    #- os: linux
    #  env: PLATFORM=amd64 DOCKERBUILD=0
    #- os: linux
    #  env: PLATFORM=i386 DOCKERBUILD=1
    - os: linux
      env: PLATFORM=armv7l DOCKERBUILD=1
    - os: linux
      env: PLATFORM=arm64 DOCKERBUILD=1

services:
  - docker

addons:
  apt:
    packages:
      - libudev-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install hidapi; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -project validation/blhost.xcodeproj; fi
  # Docker is used for cross compiling the binaries for 32-bit Linux and armv7l.
  # Build the image, create a container from the image and get the container ID,
  # then make the directory, as this is normally created automatically using Make.
  # Finally copy over the compiled binary to the host.
  - if [[ "$DOCKERBUILD" == "1" ]]; then
      docker build -f Dockerfile.$PLATFORM -t lauszus/blhost .;
      CONTAINER_ID=$(docker create lauszus/blhost);
      mkdir -p validation/blhost/gcc/Release;
      docker cp $CONTAINER_ID:/lauszus-blhost/validation/blhost/gcc/Release/blhost validation/blhost/gcc/Release/blhost;
    else
      make -j2 -C validation/blhost/gcc;
      strip validation/blhost/gcc/Release/blhost;
    fi
  # Rename the binary, so the platform is part of the name.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      mv validation/blhost/gcc/Release/blhost blhost-$PLATFORM;
    else
      mv validation/blhost/gcc/Release/blhost blhost-linux-$PLATFORM;
    fi

deploy:
  provider: releases
  api_key: 4aa475ba56ca98b8ef3d199266111087a4c526d3
  file_glob: true
  file: "blhost-*"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
